import EstimationMultivariateAnalysisCanonicalLaneLean.Basic
import EstimationMultivariateAnalysisCanonicalLaneLean.SourcePackage
import EstimationMultivariateAnalysisCanonicalLaneLean.SourceDependencies
import EstimationMultivariateAnalysisCanonicalLaneLean.Formalization
import EstimationMultivariateAnalysisCanonicalLaneLean.ReviewerBridge
import EstimationMultivariateAnalysisCanonicalLaneLean.TheoremStatement
import EstimationMultivariateAnalysisCanonicalLaneLean.MathlibObjects
import EstimationMultivariateAnalysisCanonicalLaneLean.AdmissibleClass
import EstimationMultivariateAnalysisCanonicalLaneLean.Projection
import EstimationMultivariateAnalysisCanonicalLaneLean.BridgeLemmas
import EstimationMultivariateAnalysisCanonicalLaneLean.GateLemmas
import EstimationMultivariateAnalysisCanonicalLaneLean.FinalTheorem
import EstimationMultivariateAnalysisCanonicalLaneLean.MultivariateNormalFamily
import EstimationMultivariateAnalysisCanonicalLaneLean.MeanVectorEstimation
import EstimationMultivariateAnalysisCanonicalLaneLean.CovarianceEstimation
import EstimationMultivariateAnalysisCanonicalLaneLean.HighDimensionalAsymptotics
import EstimationMultivariateAnalysisCanonicalLaneLean.ShrinkageEstimation
import EstimationMultivariateAnalysisCanonicalLaneLean.RobustEstimation

namespace HautevilleHouse
namespace EstimationMultivariateAnalysisCanonicalLaneLean

-- Root module placeholder

end EstimationMultivariateAnalysisCanonicalLaneLean
end HautevilleHouse